In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import missingno as msno
import warnings 
warnings.filterwarnings('ignore')
import numpy as np

--------------------
## 공공자전거 데이터 2305~2405 병합

In [ ]:
# CSV 파일들이 있는 폴더 경로
path = "../../Data/rent/*.csv"

# 모든 CSV 파일을 리스트로 가져옴
all_files = glob.glob(path)

# 파일들을 읽어 리스트에 저장
df_list = [pd.read_csv(file, encoding='CP949') for file in all_files]

# 모든 DataFrame을 하나로 연결
result = pd.concat(df_list, ignore_index=True)

In [ ]:
# result.to_csv('../../Data/2305~2405통합.csv', index= False)

In [ ]:
result.info()

In [3]:
df_info=pd.read_excel('../../Data/공공자전거 대여소 정보(24.6월 기준).xlsx',sheet_name='대여소현황',names=['대여소번호','대여소명','자치구','상세주소','위도','경도','설치시기','LCD','QR','운영방식'], index_col=None)
df_info

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식
0,NaN,NaN,NaN,NaN,NaN,NaN,NaT,LCD,QR,NaN
1,NaN,NaN,자치구,상세주소,위도,경도,NaT,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaT,거치\n대수,거치\n대수,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
4,301.0,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46,20,20,QR
...,...,...,...,...,...,...,...,...,...,...
2762,5872.0,서경팰리스 앞,영등포구,영등포구 가마산로 468,37.505764,126.908661,2024-03-18 00:00:00,NaN,7,QR
2763,6057.0,을지로5가(방산시장),중구,중구 동호로 369,37.567398,127.002014,2024-04-11 00:00:00,NaN,6,QR
2764,6058.0,서울도시건축전시관 옆,중구,중구 세종대로 101,37.56654,126.976845,2024-04-26 00:00:00,NaN,10,QR
2765,6059.0,덕수중학교,중구,중구 인현동2가 240-2,37.564392,126.997299,2024-06-03 00:00:00,NaN,8,QR
2766,6173.0,서울자동차운전전문학원,강서구,강서구 남부순환로 216,37.546135,126.82106,2024-03-18 00:00:00,NaN,10,QR

In [10]:
df_info=df_info.iloc[4:]

In [12]:
print(df_info.head(1))

   대여소번호          대여소명  자치구                             상세주소         위도  \
4  301.0   경복궁역 7번출구 앞  종로구  서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞  37.575794

           경도                설치시기 LCD  QR 운영방식
4  126.971451 2015-10-07 12:03:46  20  20   QR

In [ ]:
df=pd.merge(result, df_info[['대여소번호','자치구']], left_on='대여 대여소번호', right_on='대여소번호',how='left')

> 대여소 자치구 추가

In [ ]:
# df.to_csv('../../Data/통합데이터대여자치구.csv', index=False)

In [ ]:
df_info.columns

In [5]:
df=pd.read_csv('../../Data/통합데이터대여자치구.csv')

In [6]:
# df_info['대여번호']
df['반납대여소번호'].replace('\\N', np.nan,inplace=True)

In [7]:
df['반납대여소번호']=df['반납대여소번호'].astype('double')

In [ ]:
df.sort_values('대여일시')

In [6]:
df.info()
df_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51346248 entries, 0 to 51346247
Data columns (total 19 columns):
 #   Column    Dtype
---  ------    -----
 0   자전거번호     object
 1   대여일시      object
 2   대여 대여소번호  int64
 3   대여 대여소명   object
 4   대여거치대     int64
 5   반납일시      object
 6   반납대여소번호   float64
 7   반납대여소명    object
 8   반납거치대     object
 9   이용시간(분)   int64
 10  이용거리(M)   float64
 11  생년        object
 12  성별        object
 13  이용자종류     object
 14  대여대여소ID   object
 15  반납대여소ID   object
 16  자전거구분     object
 17  대여소번호     float64
 18  자치구       object
dtypes: float64(3), int64(3), object(13)
memory usage: 7.3+ GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2767 entries, 0 to 2766
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   대여소번호   2763 non-null   float64
 1   대여소명    2763 non-null   object
 2   자치구     2764 non-null   object
 3   상세주소    2764 non-null   object
 4   위도      2764 non-null   object
 5   경도      2764 non-null   object
 6   설치시기    2763 non-null   datetime64[ns]
 7   LCD     1446 non-null   object
 8   QR      1664 non-null   object
 9   운영방식    2763 non-null   object
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 216.3+ KB

In [8]:
df.head()

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간(분),이용거리(M),생년,성별,이용자종류,대여대여소ID,반납대여소ID,자전거구분,대여소번호,자치구
0,SPB-44726,2024-04-01 00:00:02,4173,중대후문 마을버스정류장,0,2024-04-01 00:00:11,4173.0,중대후문 마을버스정류장,0,0,0.0,2004,F,내국인,ST-2827,ST-2827,일반자전거,4173.0,동작구
1,SPB-69254,2024-04-01 00:00:38,1008,암사역 3번출구(국민은행앞),0,2024-04-01 00:00:48,1008.0,암사역 3번출구(국민은행앞),0,0,0.0,2003,M,내국인,ST-492,ST-492,일반자전거,1008.0,강동구
2,SPB-39654,2024-04-01 00:00:38,1531,미아사거리 1번 출구,0,2024-04-01 00:00:55,1531.0,미아사거리 1번 출구,0,0,0.0,2001,\N,내국인,ST-1105,ST-1105,일반자전거,1531.0,강북구
3,SPB-54024,2024-04-01 00:01:44,514,성수사거리 버스정류장 앞,0,2024-04-01 00:01:52,514.0,성수사거리 버스정류장 앞,0,0,0.0,1998,M,내국인,ST-112,ST-112,일반자전거,514.0,성동구
4,SPB-80138,2024-04-01 00:00:05,398,을지로3가역 3번출구,99,2024-04-01 00:01:56,4707.0,청계3가 사거리,99,1,260.0,1999,M,내국인,ST-1435,ST-2513,새싹자전거,398.0,중구

In [13]:
df_info.head()

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식
4,301.0,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07 12:03:46,20,20,QR
5,302.0,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.97406,2015-10-07 12:04:22,12,12,QR
6,303.0,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.57177,126.974663,2015-10-07 00:00:00,8,8,QR
7,305.0,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978333,2015-01-07 00:00:00,16,16,QR
8,307.0,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.57,126.9711,2015-10-07 12:09:09,11,11,QR

In [15]:
df_info.rename(columns={'자치구' : '반납 자치구'}, inplace=True)

In [17]:
info=df_info[['대여소번호','반납 자치구']]

In [18]:
info

       대여소번호 반납 자치구
4      301.0    종로구
5      302.0    종로구
6      303.0    종로구
7      305.0    종로구
8      307.0    종로구
...      ...    ...
2762  5872.0   영등포구
2763  6057.0     중구
2764  6058.0     중구
2765  6059.0     중구
2766  6173.0    강서구

[2763 rows x 2 columns]

---------------------------------------------------

In [16]:
info

       대여소번호 반납 자치구
4      301.0    종로구
5      302.0    종로구
6      303.0    종로구
7      305.0    종로구
8      307.0    종로구
...      ...    ...
2762  5872.0   영등포구
2763  6057.0     중구
2764  6058.0     중구
2765  6059.0     중구
2766  6173.0    강서구

[2763 rows x 2 columns]

In [17]:
df.columns

Index(['자전거번호', '대여일시', '대여 대여소번호', '대여 대여소명', '대여거치대', '반납일시', '반납대여소번호',
       '반납대여소명', '반납거치대', '이용시간(분)', '이용거리(M)', '생년', '성별', '이용자종류', '대여대여소ID',
       '반납대여소ID', '자전거구분', '대여소번호', '자치구'],
      dtype='object')

In [19]:
result = pd.merge(df, info, left_on='반납대여소번호', right_on='대여소번호',how='left')

In [20]:
result=result[(result['자치구'] =='송파구') | (result['반납 자치구'] =='송파구')]

In [22]:
result.to_csv('../../Data/반납추가.csv',index=False)

In [29]:
result.drop(['대여소번호_x','대여소번호_y'],axis=1, inplace= True)
result.head(1)

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간(분),이용거리(M),생년,성별,이용자종류,대여대여소ID,반납대여소ID,자전거구분,자치구,반납 자치구
7,SPB-62435,2024-04-01 00:02:22,2637,아시아지하보도 14번 출구,0,2024-04-01 00:02:35,2637.0,아시아지하보도 14번 출구,0,0,0.0,1974,\N,내국인,ST-1864,ST-1864,일반자전거,송파구,송파구

In [30]:
result.to_csv('../../Data/반납추가.csv', index=False)

In [43]:
result[result['자치구'] != '송파구']['반납 자치구'].unique()

array(['송파구'], dtype=object)

In [ ]:
result[result['반납자치구']]

In [38]:
result.value_counts('반납거치대')

반납거치대
0     5018243
99     162341
\N      19220
Name: count, dtype: int64

In [45]:
result[result['자치구'] != '송파구']

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간(분),이용거리(M),생년,성별,이용자종류,대여대여소ID,반납대여소ID,자전거구분,자치구,반납 자치구
139,SPB-33083,2024-04-01 00:01:11,2377,수서역 5번출구,0,2024-04-01 00:11:22,4480.0,가락시장 남1문 사거리,0,10,1518.06,1980,F,내국인,ST-1186,ST-2591,일반자전거,강남구,송파구
213,SPB-30061,2024-04-01 00:08:34,1019,다성이즈빌아파트(호원대 대각선 맞은편),0,2024-04-01 00:14:09,4464.0,올림픽공원 북2문 A,0,5,399.91,2000,F,내국인,ST-502,ST-2580,일반자전거,강동구,송파구
237,SPB-65530,2024-04-01 00:02:26,2377,수서역 5번출구,0,2024-04-01 00:14:47,2631.0,배명고등학교,0,12,1791.24,1991,M,내국인,ST-1186,ST-1858,일반자전거,강남구,송파구
281,SPB-47484,2024-04-01 00:04:42,1084,윤선생빌딩(JYP사옥),0,2024-04-01 00:16:14,2604.0,풍납토성 서성벽터A,0,11,1827.11,1993,\N,내국인,ST-1687,ST-1627,일반자전거,강동구,송파구
344,SPB-53547,2024-04-01 00:02:51,2377,수서역 5번출구,0,2024-04-01 00:18:13,2619.0,석촌고분역 4번출구,0,15,2761.43,1988,M,내국인,ST-1186,ST-1729,일반자전거,강남구,송파구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51345676,SPB-58749,2023-09-30 22:41:04,383,신당역 12번 출구 뒤,0,2023-10-01 00:25:11,1277.0,성내7교,0,104,17233.31,1988,M,내국인,ST-198,ST-1408,일반자전거,중구,송파구
51345825,SPB-42786,2023-09-30 23:58:12,3668,성내삼성아파트,0,2023-10-01 00:33:09,1300.0,오륜사거리,0,34,3786.79,1990,\N,내국인,ST-2740,ST-1589,일반자전거,강동구,송파구
51345929,SPB-58157,2023-09-30 23:22:58,2407,역삼서초삼성 세무서 앞 (역삼빌딩 앞),0,2023-10-01 00:41:10,1228.0,마천사거리,0,78,11500.29,1992,\N,내국인,ST-1577,ST-896,일반자전거,강남구,송파구
51346070,SPB-68085,2023-09-30 23:50:01,1063,강동롯데캐슬퍼스트 아파트(관리동),0,2023-10-01 01:05:58,2613.0,잠실나들목,0,75,14290.00,2007,M,내국인,ST-1762,ST-1705,일반자전거,강동구,송파구
51346076,SPB-49297,2023-09-30 22:12:17,2219,"고속터미널역 8-1번, 8-2번 출구 사이",0,2023-10-01 01:07:14,4483.0,잠실나들목4,0,174,10294.84,1970,\N,내국인,ST-750,ST-2593,일반자전거,서초구,송파구

In [46]:
result[(result['자치구'] == '송파구') & (result['반납 자치구'] != '송파구')]

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간(분),이용거리(M),생년,성별,이용자종류,대여대여소ID,반납대여소ID,자전거구분,자치구,반납 자치구
81,SPB-51796,2024-04-01 00:02:17,1274,영파여고 앞,0,2024-04-01 00:09:06,1029.0,성내어울터,0,6,571.17,1989,\N,내국인,ST-1092,ST-1046,일반자전거,송파구,강동구
82,SPB-45531,2024-04-01 00:02:19,1208,풍납현대아파트쉼터,0,2024-04-01 00:09:08,1084.0,윤선생빌딩(JYP사옥),0,6,1123.74,2008,M,내국인,ST-541,ST-1687,일반자전거,송파구,강동구
97,SPB-69398,2024-04-01 00:01:25,1244,문정 법조단지8,0,2024-04-01 00:09:44,2408.0,강남한양수자인아파트,0,8,936.10,2000,\N,내국인,ST-904,ST-1578,일반자전거,송파구,강남구
121,SPB-66109,2024-04-01 00:00:59,2604,풍납토성 서성벽터A,0,2024-04-01 00:10:44,1012.0,천호역효성해링턴타워 앞,0,9,1550.00,1973,\N,내국인,ST-1627,ST-496,일반자전거,송파구,강동구
165,SPB-45060,2024-04-01 00:07:31,5764,한국체육대학교,0,2024-04-01 00:12:11,1084.0,윤선생빌딩(JYP사옥),0,4,850.00,1998,F,내국인,ST-3151,ST-1687,일반자전거,송파구,강동구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51345968,SPB-57937,2023-09-30 23:46:21,4867,가락대림아파트 앞,0,2023-10-01 00:45:20,1085.0,래미안 솔베뉴(고덕로),0,59,6771.33,1991,\N,내국인,ST-2798,ST-1845,일반자전거,송파구,강동구
51346006,SPB-34828,2023-09-30 23:35:34,1201,가락시장역 3번 출구,0,2023-10-01 00:51:47,3509.0,세종사이버대학교,0,76,12743.32,1996,M,내국인,ST-838,ST-1194,일반자전거,송파구,광진구
51346050,SPB-66204,2023-09-30 23:31:09,2623,석촌동 주민센터,0,2023-10-01 01:00:49,3698.0,명일역 3번출구 옆,0,89,12660.00,1993,\N,내국인,ST-1851,ST-3085,일반자전거,송파구,강동구
51346092,SPB-57273,2023-09-30 15:49:39,4865,한성백제역 1번출구 뒤,0,2023-10-01 01:10:43,NaN,\N,\N,60,4163.00,\N,\N,비회원,ST-2797,\N,일반자전거,송파구,NaN
51346174,SPB-56463,2023-09-30 23:37:31,1222,잠실새내역 5번 출구 뒤,0,2023-10-01 01:41:24,5858.0,영등포역5번출구,0,124,21749.13,2003,M,내국인,ST-547,ST-3142,일반자전거,송파구,영등포구

---------------------

In [ ]:
df = rea